#!/usr/bin/env bash

library="$(pwd)/lib/*"
for file in $library
do
  cat "$file" | tail -n+2 >> "$(pwd)/bin/_bash"
done

cp "$(pwd)/_bash" "$1/"
echo "source $1/_bash" >> "$2"

echo "Installed _bash to $1/_bash and sourced via $2"
